spring:
  application:
    name: rpc-middleware-config-center
  #数据库配置
  datasource:
    url: jdbc:mysql://49.235.200.71:3306/rpc_middleware?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver